# Generated by Django 5.2.8 on 2025-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_type", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="changes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
